# Generated by Django 6.0.5 on 2026-05-12 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(default='Jerfson Reboques', max_length=120, verbose_name='nome da empresa')),
                ('slogan', models.CharField(default='Reboques fortes, sob medida e prontos para trabalhar', max_length=180, verbose_name='slogan')),
                ('texto_principal', models.TextField(default='Fabricamos e vendemos reboques para transporte, trabalho e lazer, com acabamento resistente e atendimento direto pelo WhatsApp.', verbose_name='texto principal')),
                ('imagem_principal', models.ImageField(blank=True, upload_to='site/', verbose_name='imagem principal')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='telefone/WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('endereco', models.CharField(blank=True, max_length=180, verbose_name='endereço')),
                ('texto_botao', models.CharField(default='Chamar no WhatsApp', max_length=60, verbose_name='texto do botão principal')),
                ('link_botao', models.URLField(blank=True, verbose_name='link do botão principal')),
                ('chamada_produtos', models.CharField(default='Modelos disponíveis', max_length=160, verbose_name='chamada dos produtos')),
                ('sobre_titulo', models.CharField(default='Construído para durar', max_length=120, verbose_name='título sobre')),
                ('sobre_texto', models.TextField(default='Cada reboque pode receber medidas, pintura, madeira, grade e acabamento conforme a necessidade do cliente.', verbose_name='texto sobre')),
            ],
            options={
                'verbose_name': 'configuração do site',
                'verbose_name_plural': 'configuração do site',
            },
        ),
        migrations.CreateModel(
            name='MensagemContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('interesse', models.CharField(blank=True, max_length=140, verbose_name='interesse')),
                ('mensagem', models.TextField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'mensagem de contato',
                'verbose_name_plural': 'mensagens de contato',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Reboque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('slug', models.SlugField(unique=True)),
                ('resumo', models.CharField(max_length=220)),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='preço')),
                ('imagem', models.ImageField(upload_to='reboques/')),
                ('capacidade', models.CharField(blank=True, max_length=80)),
                ('dimensoes', models.CharField(blank=True, max_length=80, verbose_name='dimensões')),
                ('destaque', models.BooleanField(default=False)),
                ('disponivel', models.BooleanField(default=True, verbose_name='disponível')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'reboque',
                'verbose_name_plural': 'reboques',
                'ordering': ['-destaque', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ImagemReboque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='reboques/galeria/')),
                ('legenda', models.CharField(blank=True, max_length=120)),
                ('reboque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='catalogo.reboque')),
            ],
            options={
                'verbose_name': 'imagem do reboque',
                'verbose_name_plural': 'imagens do reboque',
            },
        ),
    ]
