# Generated by Django 6.0.5 on 2026-05-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_depoimento_diferencial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='mostrar_depoimentos',
            field=models.BooleanField(default=True, verbose_name='mostrar depoimentos'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='mostrar_faixa_detalhes',
            field=models.BooleanField(default=True, verbose_name='mostrar faixa técnica nos detalhes'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='mostrar_secao_sobre',
            field=models.BooleanField(default=True, verbose_name='mostrar seção sobre/diferenciais'),
        ),
    ]
