# Generated by Django 6.0.5 on 2026-05-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_configuracaosite_mostrar_depoimentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='mostrar_link_admin',
            field=models.BooleanField(default=True, verbose_name='mostrar link do admin no menu'),
        ),
    ]
