# Generated by Django 6.0.5 on 2026-05-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_configuracaosite_mostrar_link_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='mostrar_link_contato',
            field=models.BooleanField(default=True, verbose_name='mostrar link contato no menu'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='mostrar_link_inicio',
            field=models.BooleanField(default=True, verbose_name='mostrar link início no menu'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='mostrar_link_modelos',
            field=models.BooleanField(default=True, verbose_name='mostrar link modelos no menu'),
        ),
    ]
