# Generated by Django 6.0.5 on 2026-05-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_configuracaosite_mostrar_link_contato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosite',
            name='chamada_produtos',
            field=models.CharField(blank=True, default='Modelos disponíveis', max_length=160, verbose_name='chamada dos produtos'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='nome_empresa',
            field=models.CharField(blank=True, default='Jerfson Reboques', max_length=120, verbose_name='nome da empresa'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='slogan',
            field=models.CharField(blank=True, default='Reboques fortes, sob medida e prontos para trabalhar', max_length=180, verbose_name='slogan'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='sobre_texto',
            field=models.TextField(blank=True, default='Cada reboque pode receber medidas, pintura, madeira, grade e acabamento conforme a necessidade do cliente.', verbose_name='texto sobre'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='sobre_titulo',
            field=models.CharField(blank=True, default='Construído para durar', max_length=120, verbose_name='título sobre'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='texto_botao',
            field=models.CharField(blank=True, default='Chamar no WhatsApp', max_length=60, verbose_name='texto do botão principal'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='texto_principal',
            field=models.TextField(blank=True, default='Fabricamos e vendemos reboques para transporte, trabalho e lazer, com acabamento resistente e atendimento direto pelo WhatsApp.', verbose_name='texto principal'),
        ),
    ]
