# Generated by Django 6.0.5 on 2026-05-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_alter_configuracaosite_chamada_produtos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaosite',
            name='nome_empresa',
            field=models.CharField(blank=True, default='Jerfson Reboques', max_length=120, verbose_name='nome da logo'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='slogan',
            field=models.CharField(blank=True, default='Reboques fortes, sob medida e prontos para trabalhar', max_length=180, verbose_name='título'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='texto_principal',
            field=models.TextField(blank=True, default='Fabricamos e vendemos reboques para transporte, trabalho e lazer, com acabamento resistente e atendimento direto pelo WhatsApp.', verbose_name='subtítulo'),
        ),
    ]
