# Generated by Django 6.0.5 on 2026-05-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_alter_configuracaosite_nome_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='tamanho_fonte_subtitulo',
            field=models.PositiveIntegerField(default=20, verbose_name='tamanho da fonte do subtítulo'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='tamanho_fonte_titulo',
            field=models.PositiveIntegerField(default=72, verbose_name='tamanho da fonte do título'),
        ),
    ]
