# Generated by Django 6.0.5 on 2026-05-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_configuracaosite_tamanho_fonte_subtitulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='contato_eyebrow',
            field=models.CharField(blank=True, default='Orçamento', max_length=60, verbose_name='rótulo seção contato'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='contato_passo1_texto',
            field=models.CharField(blank=True, default='Transporte, medidas, carga e uso principal.', max_length=220, verbose_name='passo 1 — texto'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='contato_passo1_titulo',
            field=models.CharField(blank=True, default='Você envia a necessidade', max_length=120, verbose_name='passo 1 — título'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='contato_passo2_texto',
            field=models.CharField(blank=True, default='Modelo, acabamento, acessórios e disponibilidade.', max_length=220, verbose_name='passo 2 — texto'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='contato_passo2_titulo',
            field=models.CharField(blank=True, default='Montamos a melhor opção', max_length=120, verbose_name='passo 2 — título'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='contato_passo3_texto',
            field=models.CharField(blank=True, default='Negociação pelo contato informado no formulário.', max_length=220, verbose_name='passo 3 — texto'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='contato_passo3_titulo',
            field=models.CharField(blank=True, default='Orçamento direto', max_length=120, verbose_name='passo 3 — título'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='contato_texto',
            field=models.TextField(blank=True, default='Informe uso, medidas desejadas e acabamento. A resposta pode vir com opções de modelo, personalização e próximos passos para fechar a compra.', verbose_name='texto seção contato'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='contato_titulo',
            field=models.CharField(blank=True, default='Conte o reboque que você precisa', max_length=120, verbose_name='título seção contato'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='depoimentos_eyebrow',
            field=models.CharField(blank=True, default='Clientes', max_length=60, verbose_name='rótulo seção depoimentos'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='depoimentos_titulo',
            field=models.CharField(blank=True, default='Quem comprou recomenda', max_length=120, verbose_name='título seção depoimentos'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='detalhe_contato_texto',
            field=models.TextField(blank=True, default='Envie seus dados e diga se quer alguma alteração de medida, pintura, madeira ou acessório. A solicitação fica salva no painel.', verbose_name='texto contato (detalhe)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='detalhe_contato_titulo',
            field=models.CharField(blank=True, default='Tenho interesse neste reboque', max_length=120, verbose_name='título contato (detalhe)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='detalhe_eyebrow',
            field=models.CharField(blank=True, default='Reboque disponível', max_length=60, verbose_name='rótulo página de detalhe'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='detalhe_passo1_texto',
            field=models.CharField(blank=True, default='O formulário já pode ir com este modelo como referência.', max_length=220, verbose_name='detalhe passo 1 — texto'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='detalhe_passo1_titulo',
            field=models.CharField(blank=True, default='Informe o interesse', max_length=120, verbose_name='detalhe passo 1 — título'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='detalhe_passo2_texto',
            field=models.CharField(blank=True, default='Explique mudanças de tamanho, carga ou acabamento.', max_length=220, verbose_name='detalhe passo 2 — texto'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='detalhe_passo2_titulo',
            field=models.CharField(blank=True, default='Ajuste sob medida', max_length=120, verbose_name='detalhe passo 2 — título'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='detalhe_passo3_texto',
            field=models.CharField(blank=True, default='Retorno pelo contato informado no formulário.', max_length=220, verbose_name='detalhe passo 3 — texto'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='detalhe_passo3_titulo',
            field=models.CharField(blank=True, default='Resposta rápida', max_length=120, verbose_name='detalhe passo 3 — título'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='detalhe_preco_info',
            field=models.CharField(blank=True, default='Solicite orçamento para medidas, acabamento e disponibilidade.', max_length=220, verbose_name='texto info preço (detalhe)'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='form_botao',
            field=models.CharField(blank=True, default='Enviar pedido de orçamento', max_length=80, verbose_name='texto do botão do formulário'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='form_subtitulo',
            field=models.CharField(blank=True, default='Quanto mais detalhes você enviar, mais certeira fica a resposta.', max_length=220, verbose_name='subtítulo do formulário'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='form_titulo',
            field=models.CharField(blank=True, default='Solicitação de orçamento', max_length=120, verbose_name='título do formulário'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='produtos_eyebrow',
            field=models.CharField(blank=True, default='Reboques', max_length=60, verbose_name='rótulo seção produtos'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='rodape_tagline',
            field=models.CharField(blank=True, default='Venda e fabricação de reboques', max_length=120, verbose_name='tagline do rodapé'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='sobre_eyebrow',
            field=models.CharField(blank=True, default='Oficina e acabamento', max_length=60, verbose_name='rótulo seção sobre'),
        ),
    ]
