# Generated by Django 6.0.5 on 2026-05-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_configuracaosite_contato_eyebrow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='tema_padrao',
            field=models.CharField(choices=[('dark', 'Escuro (padrão)'), ('light', 'Claro')], default='dark', max_length=5, verbose_name='tema padrão do site'),
        ),
    ]
