# Generated by Django 6.0.5 on 2026-05-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0010_configuracaosite_tema_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='modo_contato',
            field=models.CharField(choices=[('formulario', 'Formulário de orçamento'), ('whatsapp', 'Botão WhatsApp')], default='formulario', max_length=20, verbose_name='modo da seção de contato'),
        ),
    ]
