# Generated by Django 6.0.5 on 2026-05-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0011_modo_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='imagem_principal_mobile',
            field=models.ImageField(blank=True, help_text='Opcional. Se vazio, usa a imagem desktop no mobile também.', upload_to='site/', verbose_name='imagem principal (mobile)'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='imagem_principal',
            field=models.ImageField(blank=True, upload_to='site/', verbose_name='imagem principal (desktop)'),
        ),
    ]
