# Generated by Django 6.0.5 on 2026-05-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0012_imagem_principal_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reboque',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='reboque',
            name='resumo',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AlterField(
            model_name='reboque',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
