# Generated by Django 6.0.5 on 2026-05-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0013_reboque_campos_opcionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='opacidade_hero',
            field=models.FloatField(default=0.5, help_text='0.0 = transparente, 1.0 = totalmente escuro', verbose_name='opacidade do overlay da hero (0.0 a 1.0)'),
        ),
    ]
